version: "3.9"
services:
  otel-collector:
    image: otel/opentelemetry-collector:0.111.0
    command: ["--config=/etc/otelcol/config.yaml"]
    volumes:
      - ../minimal.yaml:/etc/otelcol/config.yaml:ro
    ports:
      - "4317:4317"
      - "4318:4318"
      - "9464:9464"
  tempo:
    image: grafana/tempo:latest
    ports:
      - "3200:3200"
  jaeger:
    image: jaegertracing/all-in-one:1.58
    ports:
      - "16686:16686"
      - "14250:14250"
  loki:
    image: grafana/loki:2.10.0
    ports:
      - "3100:3100"
  prometheus:
    image: prom/prometheus:v2.54.0
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.retention.time=2d
      - --web.enable-lifecycle
  grafana:
    image: grafana/grafana:11.2.0
    ports:
      - "3000:3000"

