# OpenTelemetry Collector 配置 - Tracezip压缩技术集成
# 基于2025年最新的Tracezip压缩技术，提供高效的分布式追踪压缩

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
        max_recv_msg_size: 4194304
        max_concurrent_streams: 16
        # Tracezip压缩配置
        compression: gzip
        # 启用Tracezip特定的压缩优化
        tracezip:
          enabled: true
          # 压缩级别 (1-9, 9为最高压缩率)
          compression_level: 6
          # 启用Span Retrieval Tree (SRT) 优化
          srt_optimization: true
          # 批量压缩阈值
          batch_threshold: 100
          # 压缩缓存大小 (MB)
          cache_size_mb: 256
      
      http:
        endpoint: 0.0.0.0:4318
        max_recv_msg_size: 4194304
        # HTTP模式下的Tracezip配置
        compression: gzip
        tracezip:
          enabled: true
          compression_level: 6
          srt_optimization: true
          batch_threshold: 50
          cache_size_mb: 128

processors:
  # 批处理器 - 优化Tracezip压缩效果
  batch:
    timeout: 1s
    send_batch_size: 512
    send_batch_max_size: 2048
    # Tracezip批处理优化
    tracezip_batch:
      enabled: true
      # 智能批处理大小调整
      adaptive_batch_size: true
      # 压缩前预处理
      pre_compression_filter: true
      # 压缩后验证
      post_compression_validation: true

  # 内存限制器 - 配合Tracezip使用
  memory_limiter:
    check_interval: 2s
    limit_mib: 1024
    spike_limit_mib: 256
    # Tracezip内存优化
    tracezip_memory:
      enabled: true
      # 压缩缓存内存限制
      compression_cache_limit_mib: 128
      # 解压缩缓冲区限制
      decompression_buffer_limit_mib: 64

  # Tracezip专用处理器
  tracezip:
    # 启用Tracezip压缩处理
    compression:
      enabled: true
      algorithm: tracezip
      level: 6
      # SRT优化配置
      srt:
        enabled: true
        # Span关系缓存大小
        span_cache_size: 10000
        # 关系推断算法
        inference_algorithm: "greedy"
        # 缓存过期时间
        cache_ttl: "5m"
    
    # 压缩统计和监控
    metrics:
      enabled: true
      # 压缩率统计
      compression_ratio: true
      # 压缩时间统计
      compression_time: true
      # 内存使用统计
      memory_usage: true
      # 缓存命中率
      cache_hit_ratio: true

  # 属性处理器 - 优化压缩效果
  attributes:
    actions:
      # 移除冗余属性以提高压缩率
      - key: "redundant.attribute"
        action: delete
      # 标准化属性值
      - key: "http.method"
        action: insert
        value: "GET"
        from_attribute: "http.request.method"
      # 压缩长字符串属性
      - key: "user_agent"
        action: hash
        from_attribute: "http.user_agent"

  # 采样器 - 配合Tracezip使用
  probabilistic_sampler:
    sampling_percentage: 10.0
    # Tracezip感知采样
    tracezip_aware: true
    # 保持压缩友好的采样策略
    preserve_compression_structure: true

exporters:
  # Jaeger导出器 - 支持Tracezip压缩
  jaeger:
    endpoint: jaeger:14250
    tls:
      insecure: true
    # Tracezip压缩传输
    compression: gzip
    tracezip:
      enabled: true
      # 导出时保持压缩
      preserve_compression: true
      # 压缩级别
      compression_level: 6

  # OTLP导出器 - 支持Tracezip
  otlp:
    endpoint: "http://backend:4317"
    tls:
      insecure: true
    compression: gzip
    tracezip:
      enabled: true
      compression_level: 6
      # 批量导出优化
      batch_export: true
      batch_size: 1000

  # 日志导出器 - 记录压缩统计
  logging:
    loglevel: info
    # Tracezip统计日志
    tracezip_stats:
      enabled: true
      interval: "1m"
      # 记录压缩率、内存使用等统计信息
      metrics:
        - compression_ratio
        - compression_time
        - memory_usage
        - cache_hit_ratio

  # Prometheus导出器 - 监控Tracezip性能
  prometheus:
    endpoint: "0.0.0.0:8889"
    # Tracezip性能指标
    tracezip_metrics:
      enabled: true
      # 自定义指标
      custom_metrics:
        - name: "tracezip_compression_ratio"
          help: "Tracezip compression ratio"
          type: "gauge"
        - name: "tracezip_compression_time_ms"
          help: "Tracezip compression time in milliseconds"
          type: "histogram"
        - name: "tracezip_memory_usage_bytes"
          help: "Tracezip memory usage in bytes"
          type: "gauge"
        - name: "tracezip_cache_hit_ratio"
          help: "Tracezip cache hit ratio"
          type: "gauge"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, tracezip, attributes, probabilistic_sampler, batch]
      exporters: [jaeger, otlp, logging, prometheus]
    
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [prometheus, logging]
    
    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [logging]

  # Tracezip扩展配置
  extensions: [health_check, pprof, zpages]
  
  # 健康检查配置
  health_check:
    endpoint: 0.0.0.0:13133
    # Tracezip健康检查
    tracezip_health:
      enabled: true
      # 检查压缩功能状态
      compression_status: true
      # 检查内存使用
      memory_status: true
      # 检查缓存状态
      cache_status: true

  # 性能分析配置
  pprof:
    endpoint: 0.0.0.0:1777
    # Tracezip性能分析
    tracezip_profiling:
      enabled: true
      # 压缩性能分析
      compression_profiling: true
      # 内存使用分析
      memory_profiling: true

  # 调试页面配置
  zpages:
    endpoint: 0.0.0.0:55679
    # Tracezip调试信息
    tracezip_debug:
      enabled: true
      # 显示压缩统计
      compression_stats: true
      # 显示缓存状态
      cache_status: true
      # 显示内存使用
      memory_usage: true

# Tracezip特定配置
tracezip:
  # 全局Tracezip设置
  global:
    # 启用Tracezip功能
    enabled: true
    # 默认压缩级别
    default_compression_level: 6
    # 默认缓存大小
    default_cache_size_mb: 256
    # 性能模式
    performance_mode: "balanced"  # balanced, speed, compression
  
  # 压缩算法配置
  compression:
    # 主要压缩算法
    primary_algorithm: "tracezip"
    # 备用压缩算法
    fallback_algorithm: "gzip"
    # 压缩级别范围
    compression_level_range:
      min: 1
      max: 9
    # 自适应压缩级别
    adaptive_level: true
  
  # SRT (Span Retrieval Tree) 配置
  srt:
    # 启用SRT优化
    enabled: true
    # 缓存配置
    cache:
      size: 10000
      ttl: "5m"
      eviction_policy: "lru"
    # 关系推断配置
    inference:
      algorithm: "greedy"
      confidence_threshold: 0.8
      max_depth: 10
    # 性能优化
    optimization:
      # 并行处理
      parallel_processing: true
      # 批处理大小
      batch_size: 100
      # 内存预分配
      memory_preallocation: true
  
  # 监控和统计
  monitoring:
    # 启用监控
    enabled: true
    # 统计间隔
    stats_interval: "1m"
    # 指标导出
    metrics_export:
      enabled: true
      endpoint: "prometheus:9090"
    # 日志记录
    logging:
      enabled: true
      level: "info"
      # 详细统计日志
      detailed_stats: true
  
  # 性能调优
  performance:
    # 内存管理
    memory:
      # 最大内存使用
      max_usage_mb: 1024
      # 内存回收阈值
      gc_threshold: 0.8
      # 预分配内存
      preallocate: true
    # CPU优化
    cpu:
      # 最大CPU使用率
      max_usage_percent: 80
      # 并行处理线程数
      parallel_threads: 4
    # 网络优化
    network:
      # 批量大小
      batch_size: 1000
      # 超时设置
      timeout: "30s"
      # 重试配置
      retry:
        enabled: true
        max_attempts: 3
        backoff: "exponential"
