# OpenTelemetry 多任务执行配置
# 基于2025年最新标准和最佳实践

execution:
  parallel_tasks: 8  # 并行任务数
  timeout: 7200      # 超时时间（秒）
  retry_count: 3     # 重试次数
  log_level: 'INFO'  # 日志级别

tasks:
  # 文档重构和优化任务
  document_restructure:
    enabled: true
    priority: 1
    script: 'scripts/document_restructure.py'
    dependencies: []
    description: '文档结构重构和优化'
    
  document_quality_check:
    enabled: true
    priority: 2
    script: 'scripts/document_quality_check.py'
    dependencies: ['document_restructure']
    description: '文档质量检查和验证'
    
  # 质量保证和验证任务
  quality_assurance:
    enabled: true
    priority: 3
    script: 'scripts/quality_assurance.py'
    dependencies: ['document_quality_check']
    description: '质量保证体系执行'
    
  formal_verification:
    enabled: true
    priority: 4
    script: 'scripts/formal_verification.py'
    dependencies: ['document_restructure']
    description: '形式化验证执行'
    
  # 标准对齐和合规任务
  standards_alignment:
    enabled: true
    priority: 5
    script: 'scripts/standards_alignment.py'
    dependencies: ['quality_assurance']
    description: '国际标准对齐检查'
    
  compliance_validation:
    enabled: true
    priority: 6
    script: 'scripts/compliance_validation.py'
    dependencies: ['standards_alignment']
    description: '合规性验证'
    
  # 社区建设和治理任务
  community_building:
    enabled: true
    priority: 7
    script: 'scripts/community_building.py'
    dependencies: ['compliance_validation']
    description: '社区建设和管理'
    
  governance_framework:
    enabled: true
    priority: 8
    script: 'scripts/governance_framework.py'
    dependencies: ['community_building']
    description: '治理框架实施'
    
  # 项目分析和报告任务
  project_analysis:
    enabled: true
    priority: 9
    script: 'scripts/project_analysis.py'
    dependencies: ['governance_framework']
    description: '项目分析和评估'
    
  case_studies:
    enabled: true
    priority: 10
    script: 'scripts/case_studies_collection.py'
    dependencies: ['project_analysis']
    description: '案例研究收集和分析'
    
  # 最终报告生成
  final_report:
    enabled: true
    priority: 11
    script: 'scripts/final_report_generator.py'
    dependencies: ['case_studies', 'formal_verification']
    description: '最终执行报告生成'

# 任务分组配置
task_groups:
  document_tasks:
    - 'document_restructure'
    - 'document_quality_check'
  
  quality_tasks:
    - 'quality_assurance'
    - 'formal_verification'
  
  standards_tasks:
    - 'standards_alignment'
    - 'compliance_validation'
  
  community_tasks:
    - 'community_building'
    - 'governance_framework'
  
  analysis_tasks:
    - 'project_analysis'
    - 'case_studies'
  
  reporting_tasks:
    - 'final_report'

# 执行策略配置
execution_strategy:
  mode: 'parallel'  # parallel, sequential, mixed
  batch_size: 4     # 批处理大小
  error_handling: 'continue'  # stop, continue, retry
  
# 监控和报告配置
monitoring:
  enable_real_time: true
  report_interval: 300  # 报告间隔（秒）
  alert_threshold: 0.8  # 告警阈值
  
# 资源限制配置
resource_limits:
  max_memory: '8GB'
  max_cpu: 80  # CPU使用率百分比
  max_disk: '50GB'
