# OpenTelemetry 2025 工作流配置文件
# Workflow Configuration for OpenTelemetry 2025

# 质量保证工作流
quality_assurance_workflow:
  name: "质量保证工作流"
  description: "执行文档质量检查、标准对齐验证和知识完整性评估"
  tasks:
    - id: "qa_document_check"
      name: "文档质量检查"
      description: "检查所有文档的质量指标"
      script_path: "scripts/automated_quality_assurance.py"
      priority: "high"
      timeout: 600
      max_retries: 2
      dependencies: []
    
    - id: "qa_standards_check"
      name: "标准对齐检查"
      description: "验证标准对齐情况"
      script_path: "scripts/standards_compliance_monitor.py"
      priority: "high"
      timeout: 300
      max_retries: 2
      dependencies: ["qa_document_check"]
    
    - id: "qa_knowledge_check"
      name: "知识完整性检查"
      description: "检查知识体系完整性"
      script_path: "scripts/knowledge_ecosystem_manager.py"
      priority: "normal"
      timeout: 400
      max_retries: 2
      dependencies: ["qa_document_check"]

# 标准合规工作流
standards_compliance_workflow:
  name: "标准合规工作流"
  description: "执行标准合规性检查和监控"
  tasks:
    - id: "sc_compliance_check"
      name: "合规性检查"
      description: "检查所有标准的合规性"
      script_path: "scripts/standards_compliance_monitor.py"
      priority: "critical"
      timeout: 500
      max_retries: 3
      dependencies: []
    
    - id: "sc_trend_analysis"
      name: "合规趋势分析"
      description: "分析合规趋势和改进建议"
      script_path: "scripts/standards_compliance_monitor.py"
      priority: "normal"
      timeout: 200
      max_retries: 2
      dependencies: ["sc_compliance_check"]

# 知识管理工作流
knowledge_management_workflow:
  name: "知识管理工作流"
  description: "执行知识体系管理和优化"
  tasks:
    - id: "km_index_build"
      name: "知识索引构建"
      description: "构建知识体系索引"
      script_path: "scripts/knowledge_ecosystem_manager.py"
      priority: "high"
      timeout: 800
      max_retries: 2
      dependencies: []
    
    - id: "km_relationship_build"
      name: "知识关系建立"
      description: "建立知识节点关系"
      script_path: "scripts/knowledge_ecosystem_manager.py"
      priority: "normal"
      timeout: 300
      max_retries: 2
      dependencies: ["km_index_build"]
    
    - id: "km_quality_assessment"
      name: "知识质量评估"
      description: "评估知识节点质量"
      script_path: "scripts/knowledge_ecosystem_manager.py"
      priority: "normal"
      timeout: 200
      max_retries: 2
      dependencies: ["km_relationship_build"]

# 综合评估工作流
comprehensive_assessment_workflow:
  name: "综合评估工作流"
  description: "执行项目综合评估和报告生成"
  tasks:
    - id: "ca_quality_assurance"
      name: "质量保证评估"
      description: "执行质量保证工作流"
      script_path: "scripts/automated_quality_assurance.py"
      priority: "high"
      timeout: 600
      max_retries: 2
      dependencies: []
    
    - id: "ca_standards_compliance"
      name: "标准合规评估"
      description: "执行标准合规工作流"
      script_path: "scripts/standards_compliance_monitor.py"
      priority: "high"
      timeout: 500
      max_retries: 2
      dependencies: []
    
    - id: "ca_knowledge_management"
      name: "知识管理评估"
      description: "执行知识管理工作流"
      script_path: "scripts/knowledge_ecosystem_manager.py"
      priority: "normal"
      timeout: 800
      max_retries: 2
      dependencies: []
    
    - id: "ca_report_generation"
      name: "综合报告生成"
      description: "生成综合评估报告"
      script_path: "scripts/automated_quality_assurance.py"
      priority: "normal"
      timeout: 300
      max_retries: 2
      dependencies: ["ca_quality_assurance", "ca_standards_compliance", "ca_knowledge_management"]

# 日常维护工作流
daily_maintenance_workflow:
  name: "日常维护工作流"
  description: "执行日常维护和监控任务"
  tasks:
    - id: "dm_health_check"
      name: "系统健康检查"
      description: "检查系统运行状态"
      command: "python -c \"import sys; print('Python version:', sys.version)\""
      priority: "normal"
      timeout: 60
      max_retries: 3
      dependencies: []
    
    - id: "dm_log_cleanup"
      name: "日志清理"
      description: "清理过期日志文件"
      command: "find . -name '*.log' -mtime +7 -delete"
      priority: "low"
      timeout: 120
      max_retries: 2
      dependencies: []
    
    - id: "dm_backup_check"
      name: "备份检查"
      description: "检查备份文件状态"
      command: "ls -la data/ 2>/dev/null || echo 'No data directory'"
      priority: "normal"
      timeout: 60
      max_retries: 2
      dependencies: []

# 紧急响应工作流
emergency_response_workflow:
  name: "紧急响应工作流"
  description: "处理紧急情况和故障恢复"
  tasks:
    - id: "er_system_diagnosis"
      name: "系统诊断"
      description: "诊断系统问题"
      command: "python -c \"import os; print('Current directory:', os.getcwd()); print('Files:', os.listdir('.'))\""
      priority: "critical"
      timeout: 120
      max_retries: 5
      dependencies: []
    
    - id: "er_error_recovery"
      name: "错误恢复"
      description: "执行错误恢复操作"
      script_path: "scripts/automated_quality_assurance.py"
      priority: "critical"
      timeout: 300
      max_retries: 5
      dependencies: ["er_system_diagnosis"]
    
    - id: "er_notification"
      name: "通知发送"
      description: "发送紧急通知"
      command: "echo 'Emergency response completed'"
      priority: "high"
      timeout: 60
      max_retries: 3
      dependencies: ["er_error_recovery"]
