# OpenTelemetry Collector 配置 - InfluxDB 集成
# 支持将 traces、metrics、logs 数据导出到 InfluxDB 时序数据库

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
        max_recv_msg_size: 4194304
        max_concurrent_streams: 16
      http:
        endpoint: 0.0.0.0:4318
        max_recv_msg_size: 4194304

processors:
  # 批处理器
  batch:
    timeout: 1s
    send_batch_size: 512
    send_batch_max_size: 2048

  # 内存限制器
  memory_limiter:
    check_interval: 2s
    limit_mib: 512
    spike_limit_mib: 128

  # 属性处理器 - 为InfluxDB优化
  attributes:
    actions:
      # 添加InfluxDB相关属性
      - key: "influxdb.measurement"
        action: insert
        value: "opentelemetry_traces"
        from_attribute: "service.name"
      - key: "influxdb.tags"
        action: insert
        value: "service,version,environment"
      # 标准化时间戳格式
      - key: "timestamp"
        action: insert
        from_attribute: "timestamp"
      # 添加数据源标识
      - key: "data_source"
        action: insert
        value: "opentelemetry"

  # 资源处理器 - 添加InfluxDB元数据
  resource:
    attributes:
      - key: "influxdb.database"
        action: insert
        value: "opentelemetry"
      - key: "influxdb.retention_policy"
        action: insert
        value: "default"
      - key: "data_format"
        action: insert
        value: "otlp"

  # 采样器
  probabilistic_sampler:
    sampling_percentage: 10.0

exporters:
  # InfluxDB 导出器 - Traces
  influxdb/traces:
    endpoint: "http://influxdb:8086"
    database: "opentelemetry_traces"
    retention_policy: "default"
    # 认证配置
    auth:
      authenticator: "basicauth/client"
    # 数据映射配置
    mapping:
      measurement: "traces"
      tags:
        - "service_name"
        - "service_version"
        - "operation_name"
        - "span_kind"
        - "status_code"
        - "environment"
      fields:
        - "duration_nanos"
        - "start_time_unix_nano"
        - "end_time_unix_nano"
        - "trace_id"
        - "span_id"
        - "parent_span_id"
      timestamp_field: "start_time_unix_nano"
    # 批处理配置
    batch:
      enabled: true
      size: 1000
      timeout: "5s"
    # 重试配置
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s
    # 队列配置
    sending_queue:
      enabled: true
      num_consumers: 10
      queue_size: 1000
    # 超时配置
    timeout: 30s

  # InfluxDB 导出器 - Metrics
  influxdb/metrics:
    endpoint: "http://influxdb:8086"
    database: "opentelemetry_metrics"
    retention_policy: "default"
    auth:
      authenticator: "basicauth/client"
    mapping:
      measurement: "metrics"
      tags:
        - "metric_name"
        - "metric_type"
        - "service_name"
        - "service_version"
        - "unit"
        - "environment"
      fields:
        - "value"
        - "timestamp"
        - "attributes"
      timestamp_field: "timestamp"
    batch:
      enabled: true
      size: 500
      timeout: "10s"
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s
    sending_queue:
      enabled: true
      num_consumers: 5
      queue_size: 500
    timeout: 30s

  # InfluxDB 导出器 - Logs
  influxdb/logs:
    endpoint: "http://influxdb:8086"
    database: "opentelemetry_logs"
    retention_policy: "default"
    auth:
      authenticator: "basicauth/client"
    mapping:
      measurement: "logs"
      tags:
        - "log_level"
        - "service_name"
        - "service_version"
        - "logger_name"
        - "environment"
      fields:
        - "log_message"
        - "timestamp"
        - "trace_id"
        - "span_id"
        - "attributes"
      timestamp_field: "timestamp"
    batch:
      enabled: true
      size: 500
      timeout: "5s"
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s
    sending_queue:
      enabled: true
      num_consumers: 5
      queue_size: 500
    timeout: 30s

  # 日志导出器 - 用于调试
  logging:
    loglevel: info
    sampling_initial: 5
    sampling_thereafter: 200

  # Prometheus 导出器 - 监控Collector自身
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: "otelcol"
    const_labels:
      service: "opentelemetry-collector"
      version: "0.91.0"

service:
  pipelines:
    # Traces 管道
    traces:
      receivers: [otlp]
      processors: [memory_limiter, resource, attributes, probabilistic_sampler, batch]
      exporters: [influxdb/traces, logging]

    # Metrics 管道
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, resource, attributes, batch]
      exporters: [influxdb/metrics, prometheus, logging]

    # Logs 管道
    logs:
      receivers: [otlp]
      processors: [memory_limiter, resource, attributes, batch]
      exporters: [influxdb/logs, logging]

  # 扩展配置
  extensions: [health_check, pprof, zpages, basicauth]

  # 健康检查
  health_check:
    endpoint: 0.0.0.0:13133

  # 性能分析
  pprof:
    endpoint: 0.0.0.0:1777

  # 调试页面
  zpages:
    endpoint: 0.0.0.0:55679

  # 基础认证
  basicauth:
    client:
      username: "opentelemetry"
      password: "changeme"

# InfluxDB 特定配置
influxdb:
  # 数据库配置
  databases:
    - name: "opentelemetry_traces"
      retention_policies:
        - name: "default"
          duration: "30d"
          replication: 1
          default: true
        - name: "long_term"
          duration: "90d"
          replication: 1
          default: false
        - name: "short_term"
          duration: "7d"
          replication: 1
          default: false
    
    - name: "opentelemetry_metrics"
      retention_policies:
        - name: "default"
          duration: "15d"
          replication: 1
          default: true
        - name: "long_term"
          duration: "30d"
          replication: 1
          default: false
    
    - name: "opentelemetry_logs"
      retention_policies:
        - name: "default"
          duration: "7d"
          replication: 1
          default: true
        - name: "long_term"
          duration: "30d"
          replication: 1
          default: false

  # 连续查询配置
  continuous_queries:
    - name: "traces_aggregation"
      database: "opentelemetry_traces"
      query: |
        SELECT mean(duration_nanos) as avg_duration,
               max(duration_nanos) as max_duration,
               min(duration_nanos) as min_duration,
               count(*) as span_count
        INTO "traces_aggregated"
        FROM "traces"
        GROUP BY time(1m), service_name, operation_name
      resample:
        every: "1m"
        for: "5m"
    
    - name: "metrics_aggregation"
      database: "opentelemetry_metrics"
      query: |
        SELECT mean(value) as avg_value,
               max(value) as max_value,
               min(value) as min_value,
               count(*) as metric_count
        INTO "metrics_aggregated"
        FROM "metrics"
        GROUP BY time(1m), metric_name, service_name
      resample:
        every: "1m"
        for: "5m"

  # 监控配置
  monitoring:
    enabled: true
    metrics:
      - name: "influxdb_database_size_bytes"
        description: "Size of InfluxDB databases in bytes"
      - name: "influxdb_measurement_count"
        description: "Number of measurements in InfluxDB"
      - name: "influxdb_write_operations_total"
        description: "Total number of write operations to InfluxDB"
      - name: "influxdb_write_errors_total"
        description: "Total number of write errors to InfluxDB"

  # 性能优化配置
  performance:
    # 批量写入配置
    batch_writing:
      enabled: true
      batch_size: 1000
      flush_interval: "5s"
      max_retries: 3
      retry_interval: "1s"
    
    # 连接池配置
    connection_pool:
      max_connections: 100
      max_idle_connections: 10
      connection_timeout: "30s"
      idle_timeout: "60s"
    
    # 压缩配置
    compression:
      enabled: true
      algorithm: "gzip"
      level: 6
    
    # 缓存配置
    cache:
      enabled: true
      size: 10000
      ttl: "5m"
      eviction_policy: "lru"

  # 数据管理配置
  data_management:
    # 数据保留策略
    retention:
      traces:
        default: "30d"
        high_volume: "7d"
        low_volume: "90d"
      metrics:
        default: "15d"
        high_frequency: "7d"
        low_frequency: "30d"
      logs:
        default: "7d"
        error_logs: "30d"
        debug_logs: "1d"
    
    # 数据压缩
    compression:
      enabled: true
      algorithm: "snappy"
      level: "fast"
    
    # 数据分片
    sharding:
      enabled: true
      shard_duration: "1d"
      shard_group_duration: "7d"
    
    # 数据备份
    backup:
      enabled: true
      schedule: "0 2 * * *"  # 每天凌晨2点
      retention: "30d"
      location: "s3://backup-bucket/influxdb/"

  # 安全配置
  security:
    # 认证配置
    authentication:
      enabled: true
      method: "basic"
      users:
        - username: "opentelemetry"
          password: "changeme"
          permissions: ["read", "write"]
        - username: "admin"
          password: "admin_password"
          permissions: ["admin"]
    
    # 授权配置
    authorization:
      enabled: true
      roles:
        - name: "reader"
          permissions: ["read"]
          databases: ["opentelemetry_traces", "opentelemetry_metrics", "opentelemetry_logs"]
        - name: "writer"
          permissions: ["read", "write"]
          databases: ["opentelemetry_traces", "opentelemetry_metrics", "opentelemetry_logs"]
        - name: "admin"
          permissions: ["admin"]
          databases: ["*"]
    
    # TLS配置
    tls:
      enabled: true
      cert_file: "/etc/ssl/certs/influxdb.crt"
      key_file: "/etc/ssl/private/influxdb.key"
      ca_file: "/etc/ssl/certs/ca.crt"
      min_version: "1.2"
      max_version: "1.3"

  # 高可用性配置
  high_availability:
    # 集群配置
    cluster:
      enabled: false
      nodes:
        - "influxdb-1:8086"
        - "influxdb-2:8086"
        - "influxdb-3:8086"
      replication_factor: 3
    
    # 负载均衡
    load_balancing:
      enabled: true
      algorithm: "round_robin"
      health_check_interval: "30s"
    
    # 故障转移
    failover:
      enabled: true
      timeout: "10s"
      max_retries: 3
